repos:

# Black
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  -   id: black

# Ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

# Check pyproject.toml
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
    - id: validate-pyproject

# Re-order Python imports
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
