from datetime import datetime, timedelta

URL_HISTORY_ATP_FILES = "http://www.tennis-data.co.uk/alldata.php"
ATP_FILE_XPATH = "/html/body/table[5]/tbody/tr[2]/td[3]/"
ATP_FILES_DIR = "data/"
ATP_HISTORY = "data/atp_history.csv"

FORMAT_DATE = "%Y-%m-%d"
TODAY = datetime.now()
TOMORROW = TODAY + timedelta(days=1)
COLS_TO_KEEP = [
    "ATP", 
    "Location", 
    "Tournament",
    "Date", 
    "Series", 
    "Court", 
    "Surface",
    "Round", 
    "Best of", 
    "Winner", 
    "Loser", 
    "WRank", 
    "LRank", 
    "WPts", 
    "LPts",
    "W1", 
    "L1", 
    "W2", 
    "L2", 
    "W3", 
    "L3", 
    "W4", 
    "L4", 
    "W5", 
    "L5", 
    "Wsets",
    "Lsets", 
    "Comment", 
    "B365W", 
    "B365L",
]

trained_algo = ""
PREFIX_MATCH_ID = "g_2_"
URL = "https://www.flashscore.fr/tennis/"
URL_MATCH_PREFIX = "https://www.flashscore.fr/match/"
URL_MATCH_SUFFIX = "/#/resume-du-match"
INVALID_STATUS = ["Annulé", "Terminé"]
PATH_DF_PRED_BEFORE = "data/data_pred_before/"
PATH_DF_PRED_DONE = "data/data_pred_done/"

PATH_MODELS = {
    "ATP_3_SETS" : "models/test",
    "ATP_5_SETS" : "",
    "WTA" : ""
}

BUTTON_NEXT_DAY = "/html/body/div[4]/div[1]/div/div/main/div[5]/div[2]/div/div[1]/div[2]/div/button[3]"
DATE_NEXT_DAY = "/html/body/div[4]/div[1]/div/div/main/div[5]/div[2]/div/div[1]/div[2]/div/button[2]"

MAPPING_SURFACE = {
    "dur": "Hard",
    "gazon": "Grass",
    "terre battue": "Clay"
}

MAPPING_TOURNAMENT = {
    "Open d'Australie": "Australian Open",
    "Internationaux de France": "French Open"
}

MAPPING_LOCATION_SERIES_ATP = {
    "Halle": "ATP500",
    "Queens Club": "ATP250",
    "Wimbledon": "Grand Slam",
    "London": "Grand Slam",
    "Bastad": "ATP250",
    "Gstaad": "ATP250",
    "Newport": "ATP250",
    "Amersfoort": "International",
    "Stuttgart": "ATP250",
    "Umag": "ATP250",
    "Kitzbuhel": "ATP250",
    "Los Angeles": "International",
    "Sopot": "International",
    "Toronto": "Masters 1000",
    "Cincinnati": "Masters 1000",
    "Indianapolis": "International",
    "Washington": "ATP500",
    "Long Island": "International",
    "US Open": "Grand Slam",
    "New York": "Grand Slam",
    "Bucharest": "ATP250",
    "Salvador": "International",
    "Tashkent": "International",
    "Hong Kong": "International",
    "Palermo": "International",
    "Moscow": "ATP250",
    "Tokyo": "ATP500",
    "Lyon": "International",
    "Vienna": "ATP500",
    "Madrid": "Masters 1000",
    "Basel": "ATP500",
    "St. Petersburg": "ATP250",
    "Stockholm": "ATP250",
    "Paris": "Grand Slam",
    "Internationaux de France": "Grand Slam",
    "French Open": "Grand Slam",
    "Shanghai": "Masters 1000",
    "Adelaide": "International",
    "Chennai": "ATP250",
    "Doha": "ATP250",
    "Auckland": "ATP250",
    "Sydney": "ATP250",
    "Melbourne": "Grand Slam",
    "Open d'Australie": "Grand Slam",
    "Australian Open": "Grand Slam",
    "Milan": "International",
    "Marseille": "ATP250",
    "San Jose": "International",
    "Vina del Mar": "International",
    "Buenos Aires": "ATP250",
    "Memphis": "International Gold",
    "Rotterdam": "ATP500",
    "Acapulco": "ATP500",
    "Copenhagen": "International",
    "Dubai ": "ATP500",
    "Delray Beach": "ATP250",
    "Scottsdale": "International",
    "Indian Wells": "Masters 1000",
    "Miami": "Masters 1000",
    "Casablanca": "ATP250",
    "Estoril ": "International",
    "Monte Carlo": "Masters 1000",
    "Barcelona": "ATP500",
    "Houston": "ATP250",
    "Munich": "ATP250",
    "Valencia": "ATP500",
    "Rome": "Masters 1000",
    "Hamburg": "ATP500",
    "St. Polten": "International",
    "Nottingham": "International",
    "'s-Hertogenbosch": "ATP250",
    "Montreal": "Masters 1000",
    "Costa Do Sauipe": "International",
    "Bangkok": "International",
    "Metz": "ATP250",
    "Vienna ": "International Gold",
    "Beijing": "ATP500",
    "New Haven": "International Gold",
    "Ho Chi Min City": "International",
    "Zagreb": "ATP250",
    "Las Vegas": "International",
    "Portschach": "International",
    "Mumbai": "International",
    "Warsaw": "International",
    "Brisbane": "ATP250",
    "Johannesburg ": "ATP250",
    "Belgrade": "ATP250",
    "Eastbourne": "ATP250",
    "Kuala Lumpur": "ATP250",
    "Santiago": "ATP250",
    "Nice": "ATP250",
    "Atlanta": "ATP250",
    "Montpellier": "ATP250",
    "Winston-Salem": "ATP250",
    "Sao Paulo": "ATP250",
    "Oeiras": "ATP250",
    "Dusseldorf": "ATP250",
    "Bogota": "ATP250",
    "Rio de Janeiro": "ATP500",
    "Shenzhen ": "ATP250",
    "Quito": "ATP250",
    "Estoril": "ATP250",
    "Istanbul": "ATP250",
    "Geneva": "ATP250",
    "Sofia": "ATP250",
    "Marrakech": "ATP250",
    "Los Cabos": "ATP250",
    "Chengdu": "ATP250",
    "Antwerp": "ATP250",
    "Budapest": "ATP250",
    "Antalya": "ATP250",
    "Pune": "ATP250",
    "Cordoba": "ATP250",
    "Zhuhai": "ATP250",
    "Cologne": "ATP250",
    "Sardinia": "ATP250",
    "Nur-Sultan": "ATP250",
    "Singapore": "ATP250",
    "Cagliari": "ATP250",
    "Marbella": "ATP250",
    "Parma": "ATP250",
    "Mallorca": "ATP250",
    "San Diego": "ATP250",
    "Turin": "Masters Cup",
    "Dallas": "ATP250",
    "Seoul": "ATP250",
    "Tel Aviv": "ATP250",
    "Florence": "ATP250",
    "Gijon": "ATP250",
    "Napoli": "ATP250",
    "Banja Luka": "ATP250"
    }

MAPPING_LOCATION_SERIES_WTA = {
    "Auckland": "International",
    "Gold Coast": "Tier 3",
    "Hobart": "International",
    "Sydney": "Premier",
    "Melbourne": "Grand Slam",
    "Tokyo": "Premier",
    "Paris": "Grand Slam",
    "Pattaya": "International",
    "Antwerp": "Tier 2",
    "Bangalore": "Tier 3",
    "Bogota": "International",
    "Dubai": "Premier",
    "Memphis": "International",
    "Acapulco": "International",
    "Doha": "Premier",
    "Indian Wells": "Premier",
    "Miami": "Premier",
    "Amelia Island": "Tier 2",
    "Charleston": "Premier",
    "Budapest": "International",
    "Estoril ": "International",
    "Warsaw": "Premier",
    "Berlin": "Tier 1",
    "Prague": "International",
    "Fes": "International",
    "Rome": "Premier",
    "Istanbul": "International",
    "Strasbourg": "International",
    "Barcelona": "International",
    "Birmingham": "International",
    "Eastbourne": "Premier",
    "'s-Hertogenbosch": "International",
    "s-Hertogenbosch": "International",
    "London": "Grand Slam",
    "Cincinnati": "Premier",
    "Palermo": "International",
    "Bad Gastein": "International",
    "Stanford": "Premier",
    "San Diego": "Tier 1",
    "Stockholm": "Tier 4",
    "Los Angeles": "Tier 2",
    "Rogers Cup": "Tier 1",
    "Forest Hills": "Tier 4",
    "New Haven": "Premier",
    "New York": "Grand Slam",
    "Bali": "Tier 3",
    "Beijing": "Premier",
    "Kolkata": "Tier 3",
    "Portoroz": "WTA250",
    "Guangzhou": "International",
    "Luxembourg": "International",
    "Seoul": "International",
    "Stuttgart": "Premier",
    "Tashkent": "International",
    "Bangkok ": "Tier 3",
    "Moscow": "Premier",
    "Zurich": "Tier 1",
    "Linz": "International",
    "Quebec": "International",
    "Madrid": "Premier",
    "Vina del Mar": "Tier 3",
    "Monreal": "Tier 1",
    "Brisbane": "Premier",
    "Monterrey": "International",
    "Marbella": "International",
    "Ponte Vedra Beach": "International",
    "Bastad": "International",
    "Toronto": "Premier",
    "Osaka": "International",
    "Kuala Lumpur": "International",
    "Copenhagen": "International",
    "Montreal": "Premier",
    "Brussels": "Premier",
    "Baku": "International",
    "College Park": "International",
    "Carlsbad": "Premier",
    "Dallas": "International",
    "Washington": "International",
    "Sofia": "International",
    "Shenzhen": "International",
    "Florianopolis": "International",
    "Katowice": "International",
    "Marrakech": "International",
    "Oeiras": "International",
    "Nürnberg": "International",
    "Rio de Janeiro": "International",
    "Bucharest": "International",
    "Hong Kong": "International",
    "Wuhan": "Premier",
    "Tianjin": "International",
    "Singapore": "Tour Championships",
    "Marrakesh": "International",
    "Nottingham": "International",
    "Zhuhai": "Tour Championships",
    "St. Petersburg": "International",
    "Kaohsiung": "International",
    "Rabat": "International",
    "Mallorca": "International",
    "Gstaad": "International",
    "Nanchang": "International",
    "Taipei": "International",
    "Biel": "International",
    "Lugano": "International",
    "San Jose": "Premier",
    "Hiroshima": "International",
    "Hua Hin": "International",
    "Lausanne": "WTA250",
    "Jurmala": "International",
    "Zhengzhou": "International",
    "Adelaide": "WTA500",
    "Lyon": "WTA250",
    "Lexington": "International",
    "Ostrava": "International",
    "Abu Dhabi": "WTA500",
    "Guadalajara": "WTA250",
    "Belgrade": "WTA250",
    "Parma": "WTA250",
    "Bad Homburg": "WTA250",
    "Hamburg": "WTA250",
    "Gdynia": "WTA250",
    "Chicago": "WTA500",
    "Cleveland": "WTA250",
    "Nur-Sultan": "WTA250",
    "Tenerife": "WTA250",
    "Cluj-Napoca": "WTA250",
    "Courmayeur": "WTA250",
    "Granby": "WTA250",
    "Chennai": "WTA250",
    "Tallinn": "WTA250",
    "Monastir": "WTA250",
    "Fort Worth": "Tour Championships"
    }

MAPPING_ROUNDS_INF_1000 = {
    "1/32 de finale": "1st Round",
    "1/16 de finale": "2nd Round",
    "1/8 de finale": "3rd Round",
    "QUARTS de finale": "Quarterfinals",
    "DEMI-FINALES": "Semifinals",
    "FINALE": "The Final",
    "ROUND ROBIN": "Round Robin"
    }

MAPPING_ROUNDS_SUP_1000 = {
    "1/64 de finale": "1st Round",
    "1/32 de finale": "2nd Round",
    "1/16 de finale": "3rd Round",
    "1/8 de finale": "4th Round",
    "QUARTS de finale": "Quarterfinals",
    "DEMI-FINALES": "Semifinals",
    "FINALE": "The Final",
    "ROUND ROBIN": "Round Robin"

}
